# spring配置文件
# 端口号
server:
  port: 2020
# 数据源 mysql
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bugai
      username: root
      password: lp516

  #  邮箱配置
  mail:
    protocol: smtp
    host: smtp.qq.com
    username:
    password:
    port: 587
    default-encoding: UTF-8
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
# 日志
logging:
  file:
    name: log/log.log
  level:
    root: info
    wuhobin: debug
# JWT
jwt:
  tokenHeader: Authorization
  secret: lp-secret
  expiration: 86400
  tokenHead: Bearer

